name: Build and Publish image to DockerHub
on: 
  [workflow_dispatch]

jobs:
  publish_image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build docker image
        run: docker build ./api -t suyashgaikwad/devops-qr-code-api:latest
      - name: push image to DockerHub
        run: | 
          docker login -u suyashgaikwad -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker push suyashgaikwad/devops-qr-code-api:latest

