name: Build and Publish image to DockerHub
on: 
  push:
    branches:
      - main
    paths:
      - 'api/Dockerfile'
      - 'front-end-nextjs/Dockerfile'
jobs:
  publish_image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build docker image
        run: |
          docker build ./api -t suyashgaikwad/devops-qr-code-api:latest
          docker build ./front-end-nextjs -t suyashgaikwad/devops-qr-code-frontend:latest
      - name: push image to DockerHub
        run: | 
          docker login -u suyashgaikwad -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker push suyashgaikwad/devops-qr-code-api:latest
          docker push suyashgaikwad/devops-qr-code-frontend:latest

